### ISSUE TITLE
Python port

### ISSUE THREAD

**Issue by JoaoFelipe** [DatabaseGroup/apted#3]
Maybe an issue is not the best place for it, but I've ported APTED to Python and I thought it would be nice to let you know: https://github.com/JoaoFelipe/apted

**Comment by mateuszpawlik** [comment]
That was a year ago but I decided to reply :-)

Thanks for your effort. We're in a process of discontinuing this repository. If you're still interested, have a look at our new [C++ Tree Similarity Library](https://github.com/DatabaseGroup/tree-similarity/tree/develop).

I'm interested how does your Python implementation perform compared to Java. Have you run any performance tests?

In a future I'd like to try [SWIG](http://www.swig.org/) to bring our library to other languages. I've already had a C# request. Let me know if you'd be interested too.
